spring:
  profiles:
    active: local

  application:
    name: travel-expense

  mustache:
    check-template-location: false

  session:
    store-type: jdbc
    timeout: 30s
    cleanup-cron: 1 * * * * *

  datasource:
    url: jdbc:postgresql://postgres:5432/travel_expense
#    url: jdbc:postgresql://localhost:5432/travel_expense
    username: postgres
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#    database-platform: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret:
            client-name: google
            authorization-grant-type: authorization_code
            scope: profile, email
            redirect-uri: "{baseUrl}/login/oauth2/code/google"
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

  mail:
    host:
    port:
    username:
    password:
    sender:
    properties:
      mail:
        smtp:
          auth:
          starttls:
            enable:
            required:
        ssl:
          enable:

org:
  jobrunr:
    background-job-server:
      enabled: true
      poll-interval-in-seconds: 5
    dashboard:
      enabled: true
      port: 8000
    jobs:
      default-number-of-retries: 3
      retry-interval: PT10S

cleanup:
  old-reports:
    cron: "0 54 10 * * *"

logging:
  level:
    org:
      springframework:
        security: DEBUG
